//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newcourt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentStaging
    {
        public string Username { get; set; }
        public int SupplierId { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
        public virtual Users Users { get; set; }
    }
}
