//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newcourt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public Suppliers()
        {
            this.Payments = new HashSet<Payments>();
            this.PaymentStaging = new HashSet<PaymentStaging>();
        }
    
        public int SupplierID { get; set; }
        public string SupplierTypeCode { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string PPSVat { get; set; }
        public string BankName { get; set; }
        public string BankAddress1 { get; set; }
        public string BankAddress2 { get; set; }
        public string BankAddress3 { get; set; }
        public string BankAddress4 { get; set; }
        public string BankAddress5 { get; set; }
        public string BankAccNumber { get; set; }
        public string SortCode { get; set; }
        public string BIC { get; set; }
        public string IBAN { get; set; }
    
        public virtual SupplierTypes SupplierTypes { get; set; }
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual ICollection<PaymentStaging> PaymentStaging { get; set; }
    }
}
