//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newcourt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemParameters
    {
        public int ID { get; set; }
        public string DatabaseVersion { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> SepaFileCount { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
        public string Phone { get; set; }
        public string VatRegNo { get; set; }
        public string PaymentRef { get; set; }
    }
}
